In [7]:
# PASO 1: ARCHIVO GEOGRAFICO (ZONAS)

import pandas as pd
import geopandas as gpd
import os

# 1. Definición de rutas
ruta_input = "../../datos/limpios"
ruta_sql = "../../datos/base_datos"

# 2. Carga delarchivo geografico y visualización
path_geojson = os.path.join(ruta_input, 'zonas', '12_NTAs_Manhattan_Geometry.geojson')
mapa_raw = gpd.read_file(path_geojson)

# 2.1 Listamos las columnas 
print("\nColumnas detectadas en el GeoJSON:")
print(mapa_raw.columns.tolist())

# 2.2 Visualización de la data
display(mapa_raw.head(10))

# 3. Conversión de Áreas - AREA_M2 a AREA_KM2
mapa_raw['AREA_M2'] = pd.to_numeric(mapa_raw['AREA_M2'], errors='coerce')
mapa_raw['AREA_KM2'] = (mapa_raw['AREA_M2'] / 1_000_000).round(4)


# 4. Seleccionamos las variables a utilziar
mapa_manhattan = mapa_raw[['ID_ZONA', 'NOMBRE_ZONA', 'NOMBRE_DISTRITO', 'AREA_KM2', 'geometry']].copy()


# 5. Exportamos los dataset (tabla y geometria)

# 5.1 Para base_datos 
df_zonas_sql = mapa_manhattan[['ID_ZONA', 'NOMBRE_ZONA', 'NOMBRE_DISTRITO','AREA_KM2']].drop_duplicates()
df_zonas_sql.to_csv(os.path.join(ruta_sql, 'zonas', 'ZONAS.csv'), index=False)

print("\n" + "="*70)
print(f"✅ Tabla ZONAS (CSV) lista en: {os.path.join(ruta_sql, 'zonas')}")
print("="*70)

# 6. Verificación

# 6.1 Verificación del Archivopara tabla de SQL
if os.path.exists(os.path.join(ruta_sql, 'zonas', 'ZONAS.csv')):
    print("\n[OK] ZONAS.csv encontrado en datos/base_datos/zonas")
    df_verif_sql = pd.read_csv(os.path.join(ruta_sql, 'zonas', 'ZONAS.csv'))
    display(df_verif_sql.head(3))
else:
    print("[ERROR] No se encontró ZONAS.csv")

Columnas detectadas en el GeoJSON:
['ID_DISTRITO', 'NOMBRE_DISTRITO', 'ID_ZONA', 'NOMBRE_ZONA', 'ID_CDTA', 'NOMBRE_CDTA', 'PERIMETRO_M', 'AREA_M2', 'geometry']

,ID_DISTRITO,NOMBRE_DISTRITO,ID_ZONA,NOMBRE_ZONA,ID_CDTA,NOMBRE_CDTA,PERIMETRO_M,AREA_M2,geometry
0,1,Manhattan,MN0101,Financial District-Battery Park City,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),44672.4863141,19226758.9064,"MULTIPOLYGON (((-74.00078 40.69429, -74.00096 ..."
1,1,Manhattan,MN0102,Tribeca-Civic Center,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),21219.504238,13578197.7714,"MULTIPOLYGON (((-73.99931 40.71755, -73.99945 ..."
2,1,Manhattan,MN0191,The Battery-Governors Island-Ellis Island-Libe...,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),49616.7910027,11993281.8692,"MULTIPOLYGON (((-74.01093 40.68449, -74.01193 ..."
3,1,Manhattan,MN0201,SoHo-Little Italy-Hudson Square,MN02,MN02 Greenwich Village-SoHo (CD 2 Equivalent),18577.1114381,12916761.4511,"MULTIPOLYGON (((-74.00282 40.72836, -74.00272 ..."
4,1,Manhattan,MN0202,Greenwich Village,MN02,MN02 Greenwich Village-SoHo (CD 2 Equivalent),12974.0060903,10600456.4919,"MULTIPOLYGON (((-73.9899 40.73443, -73.98987 4..."
5,1,Manhattan,MN0203,West Village,MN02,MN02 Greenwich Village-SoHo (CD 2 Equivalent),23882.3960537,14416861.7497,"MULTIPOLYGON (((-74.00915 40.7425, -74.00902 4..."
6,1,Manhattan,MN0301,Chinatown-Two Bridges,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),16461.541911,11541558.6972,"MULTIPOLYGON (((-73.9845 40.70951, -73.9864 40..."
7,1,Manhattan,MN0302,Lower East Side,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),22960.7636789,16473190.47,"MULTIPOLYGON (((-73.98246 40.70554, -73.98242 ..."
8,1,Manhattan,MN0303,East Village,MN03,MN03 Lower East Side-Chinatown (CD 3 Equivalent),22375.9305726,18984762.0252,"MULTIPOLYGON (((-73.96715 40.71832, -73.96656 ..."
9,1,Manhattan,MN0401,Chelsea-Hudson Yards,MN04,MN04 Chelsea-Hell's Kitchen (CD 4 Approximation),40095.2376454,29671753.5327,"MULTIPOLYGON (((-74.00179 40.76229, -74.00142 ..."

======================================================================
✅ Archivo para Proyecto guardado en: Dataset_Final
✅ Tabla DIM_ZONAS (CSV) lista en: Tablas_SQL
======================================================================

[OK] ZONAS.csv encontrado en Tablas_SQL

,ID_ZONA,NOMBRE_ZONA,NOMBRE_DISTRITO,AREA_KM2
0,MN0101,Financial District-Battery Park City,Manhattan,19.2268
1,MN0102,Tribeca-Civic Center,Manhattan,13.5782
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,Manhattan,11.9933

✅ [OK] 12_NTAs_Manhattan_Clean.geojson encontrado en Dataset_Final

,ID_ZONA,NOMBRE_ZONA,NOMBRE_DISTRITO,AREA_KM2,geometry
0,MN0101,Financial District-Battery Park City,Manhattan,19.2268,"MULTIPOLYGON (((-74.00078 40.69429, -74.00096 ..."
1,MN0102,Tribeca-Civic Center,Manhattan,13.5782,"MULTIPOLYGON (((-73.99931 40.71755, -73.99945 ..."
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,Manhattan,11.9933,"MULTIPOLYGON (((-74.01093 40.68449, -74.01193 ..."

In [30]:
# PASO 2: BLOQUE COMPETENCIA

# 1. Carga e inspección
archivo_01 = "01_Restaurantes_Manhattan.csv"
path_01 = os.path.join(ruta_input, 'competencia', archivo_01)
df_01_raw = pd.read_csv(path_01)

print(f"--- 🔍 INSPECCIÓN: {archivo_01} ---")

# 1.1 Visualizamos los datos
display(df_01_raw.head(10))

# 1.2 Verificamos tipos de datos para asegurar que las coordenadas son numéricas
df_01_raw.info()

# 2. Selección de variables y Renombrado inicial
columnas_interes = [
    'ID_RESTAURANTE', 'NOMBRE_RESTAURANTE', 'LATITUD', 'LONGITUD', 
    'COCINA', 'TIPO_COMPETENCIA'
]
df_01_filtro = df_01_raw[columnas_interes].copy()

# Renombramos COCINA a TIPO_COCINA para mayor claridad
df_01_filtro = df_01_filtro.rename(columns={'COCINA': 'TIPO_COCINA'})

# 3. Join Espacial
# Convertimos los puntos en geometría para el cruce
gdf_01 = gpd.GeoDataFrame(
    df_01_filtro, 
    geometry=gpd.points_from_xy(df_01_filtro.LONGITUD, df_01_filtro.LATITUD),
    crs="EPSG:4326"
)

# Cruzamos con 'mapa_manhattan' para obtener el ID_ZONA 
# Eliminamos NOMBRE_ZONA de la selección para evitar redundancia
df_01_unido = gpd.sjoin(
    gdf_01, 
    mapa_manhattan[['ID_ZONA', 'geometry']], 
    how="left", 
    predicate="within"
)

# Limpieza: eliminamos columnas espaciales y de sistema para el CSV final del proyecto
df_01_proyecto = df_01_unido.drop(columns=['index_right', 'geometry']).copy()

# Verificación del Join
print(f"\nRestaurantes sin barrio asignado: {df_01_proyecto['ID_ZONA'].isna().sum()}")

# 4. Exportamos la tabla para base_datos
filas_p, cols_p = df_01_proyecto.shape

# 5. Agrupación para SQL: Resumen por Barrio y Tipo de Cocina
# Agrupamos solo por ID_ZONA (la llave) y TIPO_COCINA
df_sql_01 = df_01_proyecto.groupby(['ID_ZONA', 'TIPO_COCINA']).agg(
    CLASIFICACION_COMPETENCIA=('TIPO_COMPETENCIA', 'first'),
    CANTIDAD_LOCALES=('ID_RESTAURANTE', 'count')
).reset_index()

# Guardamos el archivo final para la base de datos SQL
df_sql_01.to_csv(os.path.join(ruta_sql, 'competencia', 'RESTAURANTES.csv'), index=False)
filas_s, cols_s = df_sql_01.shape

print("\n" + "="*50)
print("✅ PASO 2 COMPLETADO: Tabla Restaurantes por Cocina")
print(f"📊 Registros procesados: {filas_p} locales individuales.")
print(f"📊 SQL: {filas_s} categorías de competencia por zona exportadas.")
print("="*50)

# Verificación de la tabla para SQL
display(df_sql_01.head(15))

--- 🔍 INSPECCIÓN: 01_Restaurantes_Manhattan.csv ---

,ID_RESTAURANTE,NOMBRE_RESTAURANTE,ZONA,NUM_EDIFICIO,CALLE,CODIGO_POSTAL,LATITUD,LONGITUD,COCINA,FECHA,VIOLACION,GRAVEDAD,PUNTAJE,CALIFICACION,ID_EDIFICIO,TIPO_COMPETENCIA
0,40359480,1 EAST 66TH STREET KITCHEN,Manhattan,1,EAST 66 STREET,10065,40.768547,-73.969581,American,2025-12-02,Dishwashing and ware washing: Cleaning and san...,Not Critical,10.0,A,1041159.0,Indirecta (Tráfico)
1,40362264,P & S DELI GROCERY,Manhattan,730,COLUMBUS AVENUE,10025,40.792621,-73.967710,American,2025-03-27,"Wiping cloths not stored clean and dry, or in ...",Critical,13.0,A,1082743.0,Indirecta (Tráfico)
2,40362274,ANGELIKA FILM CENTER,Manhattan,18,WEST HOUSTON STREET,10012,40.725744,-73.997478,American,2023-06-21,Single service article not provided. Single se...,Not Critical,11.0,A,1008240.0,Indirecta (Tráfico)
3,40363298,CAFE METRO,Manhattan,625,8 AVENUE,10018,40.756185,-73.990565,American,2025-05-01,"Food contact surface not properly washed, rins...",Critical,13.0,A,1083268.0,Indirecta (Tráfico)
4,40364347,METROPOLITAN CLUB,Manhattan,1,EAST 60 STREET,10022,40.764796,-73.972308,American,2024-10-29,"Food contact surface not properly washed, rins...",Critical,8.0,A,1081206.0,Indirecta (Tráfico)
5,40364373,ISLE OF CAPRI,Manhattan,1028,3 AVENUE,10065,40.762708,-73.965750,Italian,2024-09-10,Dishwashing and ware washing: Cleaning and san...,Not Critical,26.0,Sin Calificación,1041931.0,Indirecta (Tráfico)
6,40364389,OLD TOWN BAR,Manhattan,45,EAST 18 STREET,10003,40.737595,-73.989647,American,2025-02-26,"Food, supplies, or equipment not protected fro...",Critical,10.0,A,1016150.0,Indirecta (Tráfico)
7,40364439,SEVILLA,Manhattan,62,CHARLES STREET,10014,40.734908,-74.002973,Spanish,2025-08-21,Dishwashing and ware washing: Cleaning and san...,Not Critical,39.0,Sin Calificación,1010824.0,Indirecta (Tráfico)
8,40364443,CRIMINAL COURT BLDG CAFETERIA,Manhattan,100,CENTRE STREET,10013,40.716077,-74.001425,American,2025-08-26,Non-food contact surface or equipment made of ...,Not Critical,9.0,A,1079000.0,Indirecta (Tráfico)
9,40364467,NYAC MAIN DINING ROOM,Manhattan,180,CENTRAL PARK SOUTH,10019,40.766718,-73.978737,American,2025-01-29,Non-food contact surface or equipment made of ...,Not Critical,4.0,A,1023750.0,Indirecta (Tráfico)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6828 entries, 0 to 6827
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID_RESTAURANTE      6828 non-null   int64
 1   NOMBRE_RESTAURANTE  6828 non-null   object
 2   ZONA                6828 non-null   object
 3   NUM_EDIFICIO        6809 non-null   object
 4   CALLE               6828 non-null   object
 5   CODIGO_POSTAL       6828 non-null   int64
 6   LATITUD             6828 non-null   float64
 7   LONGITUD            6828 non-null   float64
 8   COCINA              6828 non-null   object
 9   FECHA               6828 non-null   object
 10  VIOLACION           6828 non-null   object
 11  GRAVEDAD            6828 non-null   object
 12  PUNTAJE             6828 non-null   float64
 13  CALIFICACION        6828 non-null   object
 14  ID_EDIFICIO         6774 non-null   float64
 15  TIPO_COMPETENCIA    6828 non-null   object
dtypes: float64(4), int64(2), object(10)
memory usage: 853.6+ KB

Restaurantes sin barrio asignado: 0

==================================================
✅ PASO 2 COMPLETADO: Tabla Restaurantes por Cocina
📊 Proyecto: 6828 locales individuales exportados.
📊 SQL: 618 categorías de competencia por zona exportadas.
==================================================

   ID_ZONA         TIPO_COCINA CLASIFICACION_COMPETENCIA  CANTIDAD_LOCALES
0   MN0101            American       Indirecta (Tráfico)               160
1   MN0101  Asian/Asian Fusion       Indirecta (Tráfico)                13
2   MN0101             Chicken       Indirecta (Tráfico)                 3
3   MN0101             Chinese       Indirecta (Tráfico)                12
4   MN0101              French       Indirecta (Tráfico)                12
5   MN0101              Fusion       Indirecta (Tráfico)                 1
6   MN0101               Greek       Indirecta (Tráfico)                 3
7   MN0101          Hamburgers       Indirecta (Tráfico)                10
8   MN0101              Indian       Indirecta (Tráfico)                 6
9   MN0101             Italian       Indirecta (Tráfico)                20
10  MN0101            Japanese       Indirecta (Tráfico)                12
11  MN0101              Korean       Indirecta (Tráfico)                 4
12  MN0101      Latin American         Directa (Rivales)                 3
13  MN0101       Mediterranean       Indirecta (Tráfico)                 9
14  MN0101             Mexican         Directa (Rivales)                14

In [31]:
# PASO 3: BLOQUE SEGURIDAD

# 1. Carga e inspección
archivo_02 = "02_Seguridad_Manhattan.csv"
path_02 = os.path.join(ruta_input, 'seguridad', archivo_02)
df_02_raw = pd.read_csv(path_02)

print(f"--- 🔍 INSPECCIÓN: {archivo_02} ---")

# 1.1 Visualizamos los datos
display(df_02_raw.head(10))

# 1.2 Verificamos tipos de datos
df_02_raw.info()

# 2. Transformación de delitos y lugares

# 2.1 Mapeo de delitos a TIPO_DELITO
dicc_delitos = {
    'FELONY ASSAULT': 'ASALTO GRAVE',
    'ROBBERY': 'ROBO CON VIOLENCIA',
    'BURGLARY': 'ROBO A ESTABLECIMIENTO'
}
df_02_raw['TIPO_DELITO'] = df_02_raw['DELITO'].map(dicc_delitos)

# 2.2 Categorización de lugares a LUGAR_DELITO
def categorizar_lugar(lugar):
    l = str(lugar).upper()
    if any(x in l for x in ['TRANSIT', 'SUBWAY', 'BUS', 'TAXI', 'FERRY', 'TERMINAL']):
        return 'TRANSPORTE'
    elif any(x in l for x in ['STREET', 'PARK', 'OPEN AREAS', 'HIGHWAY', 'BRIDGE', 'SIDEWALK']):
        return 'VIA PUBLICA'
    elif any(x in l for x in ['STORE', 'COMMERCIAL', 'RESTAURANT', 'SHOP', 'BANK', 'HOTEL', 'BAR', 'GYM']):
        return 'LOCAL COMERCIAL'
    elif any(x in l for x in ['RESIDENCE', 'HOUSE', 'APARTMENT']):
        return 'ZONA RESIDENCIAL'
    elif any(x in l for x in ['HOSPITAL', 'CHURCH', 'SCHOOL', 'BUILDING', 'UNIVERSITY', 'OFFICE']):
        return 'EDIFICIOS PUBLICOS'
    else:
        return 'OTROS'

df_02_raw['LUGAR_DELITO'] = df_02_raw['TIPO_LUGAR'].apply(categorizar_lugar)


# 3. Selección y Join Espacial

# Seleccionamos las columnas con los nombres definitivos
columnas_interes = ['ID_QUEJA', 'LATITUD', 'LONGITUD', 'TIPO_DELITO', 'LUGAR_DELITO']
df_02_filtro = df_02_raw[columnas_interes].copy()

gdf_02 = gpd.GeoDataFrame(
    df_02_filtro, 
    geometry=gpd.points_from_xy(df_02_filtro.LONGITUD, df_02_filtro.LATITUD),
    crs="EPSG:4326"
)

# Cruzamos con 'mapa_manhattan' para obtener solo ID_ZONA (Sin Nombre Zona para evitar redundancia)
df_02_unido = gpd.sjoin(
    gdf_02, 
    mapa_manhattan[['ID_ZONA', 'geometry']], 
    how="left", 
    predicate="within"
)

# Limpieza de columnas técnicas
df_02_proyecto = df_02_unido.drop(columns=['index_right', 'geometry']).copy()

# Verificación del Join
print(f"\nIncidentes sin barrio asignado: {df_02_proyecto['ID_ZONA'].isna().sum()}")

# 4. Exportamos los datasets

# Registros procesados para integración
filas_p, cols_p = df_02_proyecto.shape

# SQL: Tabla resumen normalizada (ID_ZONA + Tipos + Conteo)
df_sql_02 = df_02_proyecto.groupby(['ID_ZONA', 'TIPO_DELITO', 'LUGAR_DELITO']).agg(
    CANTIDAD_INCIDENTES=('ID_QUEJA', 'count')
).reset_index()

# Guardamos la tabla para SQL
df_sql_02.to_csv(os.path.join(ruta_sql, 'seguridad', 'SEGURIDAD.csv'), index=False)
filas_s, cols_s = df_sql_02.shape

print("\n" + "="*50)
print("✅ PASO 3 COMPLETADO: Tabla Seguridad Normalizada")
print(f"📊 Registros procesados: {filas_p} incidentes individuales.")
print(f"📊 SQL: {filas_s} filas con conteos por tipo y lugar.")
print("="*50)

# Verificación de la tabla final
display(df_sql_02.head(15))

--- 🔍 INSPECCIÓN: 02_Seguridad_Manhattan.csv ---

,ZONA,FECHA,HORA,ID_QUEJA,LATITUD,GRAVEDAD,LONGITUD,DELITO,TIPO_LUGAR
0,MANHATTAN,2025-04-05,01:20:00,304465601,40.704549,FELONY,-74.014290,FELONY ASSAULT,TRANSIT - NYC SUBWAY
1,MANHATTAN,2025-08-29,21:30:00,312100053,40.705582,FELONY,-74.015405,ROBBERY,HOTEL/MOTEL
2,MANHATTAN,2025-06-23,13:00:00,308510277,40.714542,FELONY,-74.015670,FELONY ASSAULT,STREET
3,MANHATTAN,2025-08-28,15:35:00,312038981,40.710832,FELONY,-74.016085,FELONY ASSAULT,PARK/PLAYGROUND
4,MANHATTAN,2025-02-21,07:42:00,301452054,40.705439,FELONY,-74.014685,ROBBERY,STREET
5,MANHATTAN,2025-05-23,13:30:00,306937819,40.704549,FELONY,-74.014290,FELONY ASSAULT,TRANSIT FACILITY (OTHER)
6,MANHATTAN,2025-02-25,08:45:00,301633409,40.714542,FELONY,-74.015670,FELONY ASSAULT,COMMERCIAL BUILDING
7,MANHATTAN,2025-03-28,11:18:00,303790483,40.716750,FELONY,-74.014661,ROBBERY,DRUG STORE
8,MANHATTAN,2025-08-16,19:15:00,311316286,40.711327,FELONY,-74.015148,FELONY ASSAULT,COMMERCIAL BUILDING
9,MANHATTAN,2025-02-04,03:00:00,300502477,40.707822,FELONY,-74.014541,ROBBERY,RESIDENCE - APT. HOUSE

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8988 entries, 0 to 8987
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ZONA        8988 non-null   object
 1   FECHA       8988 non-null   object
 2   HORA        8988 non-null   object
 3   ID_QUEJA    8988 non-null   int64
 4   LATITUD     8988 non-null   float64
 5   GRAVEDAD    8988 non-null   object
 6   LONGITUD    8988 non-null   float64
 7   DELITO      8988 non-null   object
 8   TIPO_LUGAR  8988 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 632.1+ KB

Incidentes sin barrio asignado: 0

==================================================
✅ PASO 3 COMPLETADO: Tabla Seguridad Normalizada
📊 Proyecto: 8988 incidentes individuales.
📊 SQL: 527 filas con conteos por tipo y lugar.
==================================================

   ID_ZONA             TIPO_DELITO        LUGAR_DELITO  CANTIDAD_INCIDENTES
0   MN0101            ASALTO GRAVE  EDIFICIOS PUBLICOS                    6
1   MN0101            ASALTO GRAVE     LOCAL COMERCIAL                    7
2   MN0101            ASALTO GRAVE               OTROS                    6
3   MN0101            ASALTO GRAVE          TRANSPORTE                   18
4   MN0101            ASALTO GRAVE         VIA PUBLICA                   23
5   MN0101            ASALTO GRAVE    ZONA RESIDENCIAL                    4
6   MN0101  ROBO A ESTABLECIMIENTO     LOCAL COMERCIAL                   26
7   MN0101  ROBO A ESTABLECIMIENTO               OTROS                    9
8   MN0101  ROBO A ESTABLECIMIENTO         VIA PUBLICA                    1
9   MN0101  ROBO A ESTABLECIMIENTO    ZONA RESIDENCIAL                    9
10  MN0101      ROBO CON VIOLENCIA     LOCAL COMERCIAL                   26
11  MN0101      ROBO CON VIOLENCIA               OTROS                   10
12  MN0101      ROBO CON VIOLENCIA          TRANSPORTE                   10
13  MN0101      ROBO CON VIOLENCIA         VIA PUBLICA                   22
14  MN0101      ROBO CON VIOLENCIA    ZONA RESIDENCIAL                    2

In [32]:
# PASO 4: BLOQUE MOVILIDAD (MTA)

# 1. Carga e inspección
archivo_10 = "10_MTA_Manhattan.csv"
path_10 = os.path.join(ruta_input, 'movilidad', archivo_10)
df_10_raw = pd.read_csv(path_10)

print(f"--- 🔍 INSPECCIÓN: {archivo_10} ---")

# 1.1 Visualizamos los datos 
display(df_10_raw.head(10))

# 1.2 Verificamos tipos de datos
df_10_raw.info()

# 2. PROCESAMIENTO: Agregación por Estación y Tipo de Día
# Agregamos por día (Sumamos los pasajeros que pasaron entre 10am y 10pm)
df_diario = df_10_raw.groupby(['ID_ESTACION', 'ESTACION', 'LATITUD', 'LONGITUD', 'FECHA', 'TIPO_DIA']).agg(
    TOTAL_PASAJEROS_DIA=('PASAJEROS', 'sum')
).reset_index()

# Calculamos el PROMEDIO DIARIO (Laborable vs Fin de Semana)
df_mta_promedio = df_diario.groupby(['ID_ESTACION', 'ESTACION', 'LATITUD', 'LONGITUD', 'TIPO_DIA']).agg(
    PROMEDIO_DIARIO_PASAJEROS=('TOTAL_PASAJEROS_DIA', 'mean')
).reset_index()

# Convertimos a ENTERO para que sea un número de personas real
df_mta_promedio['PROMEDIO_DIARIO_PASAJEROS'] = df_mta_promedio['PROMEDIO_DIARIO_PASAJEROS'].round(0).astype(int)

# 3. Join Espacial (Asignar ID_ZONA)
gdf_mta = gpd.GeoDataFrame(
    df_mta_promedio, 
    geometry=gpd.points_from_xy(df_mta_promedio.LONGITUD, df_mta_promedio.LATITUD),
    crs="EPSG:4326"
)

# Cruzamos con 'mapa_manhattan' para obtener solo ID_ZONA (Sin Nombre de Zona por normalización)
df_mta_unido = gpd.sjoin(
    gdf_mta, 
    mapa_manhattan[['ID_ZONA', 'geometry']], 
    how="left", 
    predicate="within"
)

# Si quedan nulos, usamos 'sjoin_nearest' para que busquen el barrio más cercano 
if df_mta_unido['ID_ZONA'].isna().any():
    # Separamos los nulos
    nulos = df_mta_unido[df_mta_unido['ID_ZONA'].isna()].copy()
    nulos = nulos.drop(columns=['ID_ZONA', 'index_right'])
    
    # PROYECTAMOS A METROS (EPSG:2263 es para NY) para que el cálculo sea exacto
    nulos_proy = nulos.to_crs("EPSG:2263")
    mapa_proy = mapa_manhattan.to_crs("EPSG:2263")
    
    # Buscamos el vecino más cercano
    nulos_corregidos = gpd.sjoin_nearest(
        nulos_proy, 
        mapa_proy[['ID_ZONA', 'geometry']], 
        how="left"
    )
    
    # Volvemos a unir los datos corregidos al dataframe principal
    df_mta_unido = pd.concat([
        df_mta_unido[df_mta_unido['ID_ZONA'].notna()], 
        nulos_corregidos.to_crs("EPSG:4326")
    ])

# Limpieza final del Join
df_mta_final = df_mta_unido.drop(columns=['index_right', 'geometry']).copy()

# 4. Exportamos los datasets

# Registros procesados para integración
filas_p, cols_p = df_mta_final.shape

# SQL: Resumen por Barrio y Tipo de Día (Normalizada: Solo ID_ZONA)
df_sql_10 = df_mta_final.groupby(['ID_ZONA', 'TIPO_DIA']).agg(
    VOLUMEN_TOTAL_PASAJEROS=('PROMEDIO_DIARIO_PASAJEROS', 'sum'),
    CANTIDAD_ESTACIONES=('ID_ESTACION', 'nunique')
).reset_index()

# Aseguramos que el resultado sea un número entero limpio
df_sql_10['VOLUMEN_TOTAL_PASAJEROS'] = df_sql_10['VOLUMEN_TOTAL_PASAJEROS'].astype(int)

# Guardamos la tabla definitiva para la base de datos
df_sql_10.to_csv(os.path.join(ruta_sql, 'movilidad', 'MOVILIDAD.csv'), index=False)
filas_s, cols_s = df_sql_10.shape

print("\n" + "="*60)
print("✅ MOVILIDAD ACTUALIZADA: Tabla normalizada para SQL")
print(f"📊 Registros procesados: {filas_p} registros de estaciones.")
print(f"📊 SQL: {filas_s} filas con flujos agregados por zona.")
print("="*60)

# Verificación: Barrios con mayor flujo de personas
display(df_sql_10.sort_values(by='VOLUMEN_TOTAL_PASAJEROS', ascending=False).head(10))

--- 🔍 INSPECCIÓN: 10_MTA_Manhattan_II.csv ---

,ESTACION,ID_ESTACION,ZONA,PASAJEROS,LATITUD,LONGITUD,FECHA,HORA,TIPO_DIA
0,1 Av (L),119,Manhattan,3.0,40.730953,-73.981630,2024-10-01,10,Laborable
1,207 St (1),298,Manhattan,9.0,40.864620,-73.918820,2024-10-01,10,Laborable
2,"Lexington Av/63 St (F,Q)",223,Manhattan,63.0,40.764630,-73.966110,2024-10-01,10,Laborable
3,"135 St (2,3)",438,Manhattan,165.0,40.814228,-73.940770,2024-10-01,10,Laborable
4,"Lexington Av (N,R,W)/59 St (4,5,6)",613,Manhattan,16.0,40.762660,-73.967255,2024-10-01,10,Laborable
5,Cathedral Pkwy (110 St) (1),308,Manhattan,38.0,40.803967,-73.966850,2024-10-01,10,Laborable
6,23 St (6),405,Manhattan,22.0,40.739864,-73.986600,2024-10-01,10,Laborable
7,145 St (1),304,Manhattan,19.0,40.826550,-73.950360,2024-10-01,10,Laborable
8,Harlem-148 St (3),436,Manhattan,12.0,40.823880,-73.936470,2024-10-01,10,Laborable
9,125 St (1),306,Manhattan,8.0,40.815582,-73.958374,2024-10-01,10,Laborable

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465343 entries, 0 to 465342
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   ESTACION     465343 non-null  object
 1   ID_ESTACION  465343 non-null  object
 2   ZONA         465343 non-null  object
 3   PASAJEROS    465343 non-null  float64
 4   LATITUD      465343 non-null  float64
 5   LONGITUD     465343 non-null  float64
 6   FECHA        465343 non-null  object
 7   HORA         465343 non-null  int64
 8   TIPO_DIA     465343 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 32.0+ MB

============================================================
✅ MOVILIDAD ACTUALIZADA: Tabla normalizada para SQL
📊 Proyecto: 315 registros de estaciones exportados.
📊 SQL: 62 filas con flujos agregados por zona.
============================================================

   ID_ZONA       TIPO_DIA  VOLUMEN_TOTAL_PASAJEROS  CANTIDAD_ESTACIONES
23  MN0502      Laborable                   143758                   10
21  MN0501      Laborable                   123072                    9
22  MN0502  Fin de Semana                   116060                   10
37  MN0802      Laborable                    83903                    6
20  MN0501  Fin de Semana                    83012                    9
1   MN0101      Laborable                    78390                   10
17  MN0401      Laborable                    65068                    6
3   MN0102      Laborable                    58553                    6
0   MN0101  Fin de Semana                    54974                   10
5   MN0201      Laborable                    51431                    6

In [33]:
# PASO 5: BLOQUE LUGARES DE INTERÉS (11 - Common Places)

# 1. Carga e inspección
archivo_11 = "11_Common_Places_Manhattan.csv"
path_11 = os.path.join(ruta_input, 'lugares_interes', archivo_11)
df_11_raw = pd.read_csv(path_11)

print(f"--- 🔍 INSPECCIÓN: {archivo_11} ---")

# 1.1 Visualizamos los datos 
display(df_11_raw.head(10))

# 1.2 Verificamos tipos de datos
df_11_raw.info()

# 1.3 Revisamos las categorías únicas y renombramos la columna
print("\nCategorías detectadas en Lugares Comunes:")
print(df_11_raw['CATEGORIA'].unique())

# Renombramos CATEGORIA a CATEGORIA_LUGAR para mayor claridad técnica
df_11_raw = df_11_raw.rename(columns={'CATEGORIA': 'CATEGORIA_LUGAR'})

# 2. Selección de variables
columnas_interes = ['NOMBRE_LUGAR', 'CATEGORIA_LUGAR', 'LATITUD', 'LONGITUD']
df_11_filtro = df_11_raw[columnas_interes].copy()

# 3. Join Espacial
# Convertimos a geometría
gdf_11 = gpd.GeoDataFrame(
    df_11_filtro, 
    geometry=gpd.points_from_xy(df_11_filtro.LONGITUD, df_11_filtro.LATITUD),
    crs="EPSG:4326"
)

# Cruzamos con 'mapa_manhattan' para asignar solo el ID_ZONA (Normalización)
df_11_unido = gpd.sjoin(
    gdf_11, 
    mapa_manhattan[['ID_ZONA', 'geometry']], 
    how="left", 
    predicate="within"
)

# 3.1 Corrección de puntos fuera de límites (Sjoin Nearest)
if df_11_unido['ID_ZONA'].isna().any():
    nulos = df_11_unido[df_11_unido['ID_ZONA'].isna()].copy()
    nulos = nulos.drop(columns=['ID_ZONA', 'index_right'])
    
    # Proyectamos a metros para precisión en el borde de la isla (EPSG:2263 NY)
    nulos_proy = nulos.to_crs("EPSG:2263")
    mapa_proy = mapa_manhattan.to_crs("EPSG:2263")
    
    nulos_corregidos = gpd.sjoin_nearest(
        nulos_proy, 
        mapa_proy[['ID_ZONA', 'geometry']], 
        how="left"
    )
    
    # Combinamos resultados
    df_11_unido = pd.concat([
        df_11_unido[df_11_unido['ID_ZONA'].notna()], 
        nulos_corregidos.to_crs("EPSG:4326")
    ])

# Limpieza de columnas técnicas del Join
df_11_proyecto = df_11_unido.drop(columns=['index_right', 'geometry']).copy()

# Verificación final
print(f"✅ Lugares sin barrio tras la corrección: {df_11_proyecto['ID_ZONA'].isna().sum()}")
display(df_11_proyecto.head(5))

# 4. Exportamos los datasets

filas_p, cols_p = df_11_proyecto.shape

# 5. Tabla para SQL (Normalizada: ID_ZONA + CATEGORIA_LUGAR)
df_sql_11 = df_11_proyecto.groupby(['ID_ZONA', 'CATEGORIA_LUGAR']).agg(
    CANTIDAD_LUGARES=('NOMBRE_LUGAR', 'count')
).reset_index()

# Guardamos la tabla para SQL
df_sql_11.to_csv(os.path.join(ruta_sql, 'lugares_interes', 'LUGARES_INTERES.csv'), index=False)
filas_s, cols_s = df_sql_11.shape

print("\n" + "="*50)
print("✅ PASO 5 COMPLETADO: Tabla Lugares Normalizada")
print(f"📊 Registros procesados: {filas_p} lugares individuales.")
print(f"📊 SQL: {filas_s} categorías por zona exportadas.")
print("="*50)

# Verificación de la tabla para SQL
display(df_sql_11.head(15))

--- 🔍 INSPECCIÓN: 11_Common_Places_Manhattan.csv ---

,NOMBRE_LUGAR,CATEGORIA,ZONA,LONGITUD,LATITUD
0,THOMAS JEFFERSON PARK,Parques y Jardines,Manhattan,-73.936113,40.793070
1,DALTON SCHOOL THE FIRST PROGRAM,Educacion,Manhattan,-73.955889,40.783952
2,STUYVESANT TOWN 321 AVE C 319 AVE C 315 AVE C,Residencial,Manhattan,-73.974551,40.731826
3,HARLEM GROWN 134 ST GREEN HOUSE,Parques y Jardines,Manhattan,-73.943313,40.814106
4,RIVERSIDE PARK BASKETBALL COURTS W 111 ST,Parques y Jardines,Manhattan,-73.969750,40.806235
5,THE STANDARD HOTEL EAST VILLAGE,Comercial y Hoteles,Manhattan,-73.990796,40.727859
6,PUBLIC SCHOOL 139 CONVERSION,Residencial,Manhattan,-73.940134,40.817739
7,NEW YORK UNIVERSITY STUDENT HEALTH CENTER,Educacion,Manhattan,-73.993122,40.729298
8,PS 200 THE JAMES MCCUNE SMITH SCHOOL,Educacion,Manhattan,-73.936123,40.824321
9,RANDALLS ISLAND FIELD 63,Parques y Jardines,Manhattan,-73.924540,40.782980

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4253 entries, 0 to 4252
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NOMBRE_LUGAR  4253 non-null   object
 1   CATEGORIA     4253 non-null   object
 2   ZONA          4253 non-null   object
 3   LONGITUD      4253 non-null   float64
 4   LATITUD       4253 non-null   float64
dtypes: float64(2), object(3)
memory usage: 166.3+ KB

Categorías detectadas en Lugares Comunes:
['Parques y Jardines' 'Educacion' 'Residencial' 'Comercial y Hoteles'
 'Cultura' 'Administracion Publica' 'Monumentos y Plazas']
✅ Lugares sin barrio tras la corrección: 0

,NOMBRE_LUGAR,CATEGORIA_LUGAR,LATITUD,LONGITUD,ID_ZONA
0,THOMAS JEFFERSON PARK,Parques y Jardines,40.793070,-73.936113,MN1102
1,DALTON SCHOOL THE FIRST PROGRAM,Educacion,40.783952,-73.955889,MN0802
2,STUYVESANT TOWN 321 AVE C 319 AVE C 315 AVE C,Residencial,40.731826,-73.974551,MN0601
3,HARLEM GROWN 134 ST GREEN HOUSE,Parques y Jardines,40.814106,-73.943313,MN1002
4,RIVERSIDE PARK BASKETBALL COURTS W 111 ST,Parques y Jardines,40.806235,-73.969750,MN0901

==================================================
✅ PASO 5 COMPLETADO: Tabla Lugares Normalizada
📊 Proyecto: 4254 lugares individuales exportados.
📊 SQL: 232 categorías por zona exportadas.
==================================================

   ID_ZONA         CATEGORIA_LUGAR  CANTIDAD_LUGARES
0   MN0101  Administracion Publica                12
1   MN0101     Comercial y Hoteles                41
2   MN0101                 Cultura                21
3   MN0101               Educacion                25
4   MN0101     Monumentos y Plazas                37
5   MN0101      Parques y Jardines                23
6   MN0101             Residencial                 6
7   MN0102  Administracion Publica                26
8   MN0102     Comercial y Hoteles                 3
9   MN0102                 Cultura                 2
10  MN0102               Educacion                16
11  MN0102     Monumentos y Plazas                 8
12  MN0102      Parques y Jardines                15
13  MN0102             Residencial                 1
14  MN0191  Administracion Publica                 2

In [34]:
# PASO 6.1: BLOQUE CENSO - POBLACIÓN 

pd.set_option('display.max_columns', None)

# 1. Carga e inspección
archivo_03 = "03_Censo_Age_Sex_Manhattan.csv"
path_03 = os.path.join(ruta_input, 'censo', archivo_03)
df_03_raw = pd.read_csv(path_03)

# Visualizamos para identificar los nombres exactos de las columnas de población y edad
display(df_03_raw.head(5))
df_03_raw.info()

# 2. Selección de variables y limpieza de nombres
df_03_filtro = df_03_raw[['Zona_Codigo', 'Total Poblacion', 'Media de Edad']].copy()

# Renombramos para estandarizar con base maestra
df_03_filtro = df_03_filtro.rename(columns={
    'Zona_Codigo': 'ID_ZONA',
    'Total Poblacion': 'POBLACION_TOTAL',
    'Media de Edad': 'EDAD_MEDIANA'
})

# 5. Métricas de exportación
filas, cols = df_03_filtro.shape

# 7. Verificación de Calidad
print("\n" + "="*70)
print(f" VERIFICACION DE LOS DATOS")
print(f"✅ Variable POBLACION_TOTAL: Rango [{df_03_filtro['POBLACION_TOTAL'].min()} - {df_03_filtro['POBLACION_TOTAL'].max()}]")
print(f"✅ Variable EDAD_MEDIANA: Promedio general de Manhattan: {df_03_filtro['EDAD_MEDIANA'].mean():.2f}")

print("\n" + "="*70)
print(f"✅ PASO 6.1 COMPLETADO: {archivo_03}")
print(f"📊 Variables: ID_ZONA, POBLACION_TOTAL, EDAD_MEDIANA")
print(f"📊 Dataset: {filas} filas y {cols} columnas.")
print("="*70)

display(df_03_filtro.head(31))

,Zona_Nombre,Zona_Codigo,Total Poblacion,Total Male,Total Female,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 29 years,30 to 34 years,35 to 39 years,40 to 44 years,45 to 49 years,50 to 54 years,55 to 59 years,60 to 64 years,65 to 69 years,70 to 74 years,75 to 79 years,80 to 84 years,85 years and over,Media de Edad
0,Chelsea-Hudson Yards,MN0401,61878,31602,30276,1748,1574,1495,1917,3316,8076,8922,4597,4108,4002,3788,4934,3972,2613,2841,1821,1212,942,39.2
1,East Harlem (North),MN1102,63526,29728,33798,3484,3590,4139,3124,4180,5610,5991,5041,4443,3807,4329,3958,3102,2374,2091,1553,1065,1645,36.6
2,East Harlem (South),MN1101,58607,24994,33613,3289,2425,3203,3078,4026,5032,5285,5319,2967,3260,3326,3463,3557,3956,2270,1942,1033,1176,37.8
3,East Midtown-Turtle Bay,MN0604,41969,19314,22655,1702,1077,1058,787,1636,4487,4259,3529,2231,1705,2740,2051,2912,2293,2883,2669,1849,2101,45.6
4,East Village,MN0303,68412,33605,34807,1968,1260,1559,4769,7706,8873,10285,4126,3310,2951,3229,4713,3471,3209,2748,1526,1322,1387,33.9

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Zona_Nombre        31 non-null     object
 1   Zona_Codigo        31 non-null     object
 2   Total Poblacion    31 non-null     int64
 3   Total Male         31 non-null     int64
 4   Total Female       31 non-null     int64
 5   Under 5 years      31 non-null     int64
 6   5 to 9 years       31 non-null     int64
 7   10 to 14 years     31 non-null     int64
 8   15 to 19 years     31 non-null     int64
 9   20 to 24 years     31 non-null     int64
 10  25 to 29 years     31 non-null     int64
 11  30 to 34 years     31 non-null     int64
 12  35 to 39 years     31 non-null     int64
 13  40 to 44 years     31 non-null     int64
 14  45 to 49 years     31 non-null     int64
 15  50 to 54 years     31 non-null     int64
 16  55 to 59 years     31 non-null     int64
 17  60 to 64 years     31 non-null     int64
 18  65 to 69 years     31 non-null     int64
 19  70 to 74 years     31 non-null     int64
 20  75 to 79 years     31 non-null     int64
 21  80 to 84 years     31 non-null     int64
 22  85 years and over  31 non-null     int64
 23  Media de Edad      31 non-null     float64
dtypes: float64(1), int64(21), object(2)
memory usage: 5.9+ KB

======================================================================
 VERIFICACION DE LOS DATOS
✅ Variable POBLACION_TOTAL: Rango [21949 - 99128]
✅ Variable EDAD_MEDIANA: Promedio general de Manhattan: 38.71

======================================================================
✅ PASO 6.1 COMPLETADO: 03_Censo_Age_Sex_Manhattan.csv
📊 Variables: ID_ZONA, POBLACION_TOTAL, EDAD_MEDIANA
📊 Dataset: 31 filas y 3 columnas.
======================================================================

   ID_ZONA  POBLACION_TOTAL  EDAD_MEDIANA
0   MN0401            61878          39.2
1   MN1102            63526          36.6
2   MN1101            58607          37.8
3   MN0604            41969          45.6
4   MN0303            68412          33.9
5   MN0101            48608          34.3
6   MN0602            26523          35.2
7   MN0202            31517          35.7
8   MN0903            52530          38.0
9   MN1002            86090          38.1
10  MN1001            48803          38.3
11  MN0402            55221          39.1
12  MN1203            38209          38.5
13  MN0302            46107          42.2
14  MN0902            22260          34.5
15  MN0501            29670          35.2
16  MN0502            21949          42.8
17  MN0901            37984          28.1
18  MN0603            54905          34.3
19  MN0201            22167          39.3
20  MN0601            21963          39.6
21  MN0102            23257          36.8
22  MN0802            54062          50.0
23  MN0801            79296          37.9
24  MN0803            78950          42.2
25  MN0702            99128          44.9
26  MN0701            68212          43.2
27  MN0703            51421          40.5
28  MN1202            75554          40.0
29  MN1201            74814          38.4
30  MN0203            32518          39.7

In [35]:
# PASO 6.2: BLOQUE CENSO - ORIGEN HISPANO

pd.set_option('display.max_columns', None)

# 1. Carga e inspección
archivo_04 = "04_Censo_Hispanic_Origin_Manhattan.csv"
path_04 = os.path.join(ruta_input, 'censo', archivo_04)
df_04_raw = pd.read_csv(path_04)

#visualizamos
display(df_04_raw.head(5))

# 2. AGRUPACIÓN: Sumamos la población por 'Grupo'
df04_agrupado = df_04_raw.groupby(['Zona_Nombre', 'Zona_Codigo', 'Grupo'])['Poblacion'].sum().reset_index()

# 3. PIVOTAJE: Convertimos los grupos en columnas
df04_pivot = df04_agrupado.pivot(
    index=['Zona_Nombre', 'Zona_Codigo'], 
    columns='Grupo', 
    values='Poblacion'
).reset_index()

# 4. RENOMBRADO Y SELECCIÓN: Estandarizamos nombres
df04_refinado = df04_pivot.rename(columns={
    'Zona_Codigo': 'ID_ZONA',
    'Hispanic or Latino': 'POBLACION_HISPANA'
})

# 5. UNIÓN A LA BASE MAESTRA (union con la data anterior de poblacion)
    
df_censo_consolidado = pd.merge(
    df_03_filtro, 
    df04_refinado[['ID_ZONA', 'POBLACION_HISPANA']], 
    on='ID_ZONA', 
    how='left'
)

# 6. Verificación de Calidad
filas, cols = df_censo_consolidado.shape
print("\n" + "="*70)
print(f"✅ PASO 6.2 COMPLETADO: Unión de {archivo_04}")
print(f"📊 Variables actuales: {df_censo_consolidado.columns.tolist()}")
print(f"📊 Dataset actual: {filas} filas y {cols} columnas.")
print(f"🏠 Poblacion Hispana: [{df_censo_consolidado['POBLACION_HISPANA'].min()} - {df_censo_consolidado['POBLACION_HISPANA'].max()}]")

print("="*70)

display(df_censo_consolidado.head(31))

,Zona_Nombre,Zona_Codigo,Grupo,Subgrupo,Poblacion
0,Chelsea-Hudson Yards,MN0401,Hispanic or Latino,Mexican,881
1,Chelsea-Hudson Yards,MN0401,Hispanic or Latino,Puerto Rican,3474
2,Chelsea-Hudson Yards,MN0401,Hispanic or Latino,Cuban,214
3,Chelsea-Hudson Yards,MN0401,Hispanic or Latino,Dominican (Dominican Republic),1435
4,Chelsea-Hudson Yards,MN0401,Central American,Costa Rican,16

======================================================================
✅ PASO 6.2 COMPLETADO: Unión de 04_Censo_Hispanic_Origin_Manhattan.csv
📊 Variables actuales: ['ID_ZONA', 'POBLACION_TOTAL', 'EDAD_MEDIANA', 'POBLACION_HISPANA']
📊 Dataset actual: 31 filas y 4 columnas.
🏠 Poblacion Hispana: [849 - 41937]
======================================================================

   ID_ZONA  POBLACION_TOTAL  EDAD_MEDIANA  POBLACION_HISPANA
0   MN0401            61878          39.2               6004
1   MN1102            63526          36.6              21871
2   MN1101            58607          37.8              19369
3   MN0604            41969          45.6               1721
4   MN0303            68412          33.9              11928
5   MN0101            48608          34.3               1639
6   MN0602            26523          35.2                849
7   MN0202            31517          35.7               1003
8   MN0903            52530          38.0              19999
9   MN1002            86090          38.1              18165
10  MN1001            48803          38.3               6565
11  MN0402            55221          39.1               6556
12  MN1203            38209          38.5              23226
13  MN0302            46107          42.2              12016
14  MN0902            22260          34.5               9922
15  MN0501            29670          35.2               1493
16  MN0502            21949          42.8               1069
17  MN0901            37984          28.1               4722
18  MN0603            54905          34.3               2830
19  MN0201            22167          39.3                975
20  MN0601            21963          39.6               1097
21  MN0102            23257          36.8                873
22  MN0802            54062          50.0               2153
23  MN0801            79296          37.9               2959
24  MN0803            78950          42.2               4723
25  MN0702            99128          44.9               7618
26  MN0701            68212          43.2               3982
27  MN0703            51421          40.5               9724
28  MN1202            75554          40.0              37752
29  MN1201            74814          38.4              41937
30  MN0203            32518          39.7               2364

In [36]:
# PASO 6.3: BLOQUE CENSO - TOTAL VIVIENDAS

pd.set_option('display.max_columns', None)

# 1. Carga e inspección
archivo_05 = "05_Censo_Household_Type_Manhattan.csv"
path_05 = os.path.join(ruta_input, 'censo', archivo_05)
df_05_raw = pd.read_csv(path_05)

# Visualizamos
display(df_05_raw.head(5))

# 2. Seleccion
df_05_refinado = df_05_raw[['Zona_Codigo', 'Average household size']].copy()

# Renombramos
df_05_refinado = df_05_refinado.rename(columns={
    'Zona_Codigo': 'ID_ZONA',
    'Average household size': 'TAMANO_HOGAR_PROMEDIO'
})

# 3. UNIÓN AL CONSOLIDADO 
# Antes, borramos si existe por error previo
if 'TAMANO_HOGAR_PROMEDIO' in df_censo_consolidado.columns:
    df_censo_consolidado = df_censo_consolidado.drop(columns=['TAMANO_HOGAR_PROMEDIO'])
    
df_censo_consolidado = pd.merge(
    df_censo_consolidado, 
    df_05_refinado[['ID_ZONA', 'TAMANO_HOGAR_PROMEDIO']], 
    on='ID_ZONA', 
    how='left'
)

# 4. Verificación de Calidad
filas, cols = df_censo_consolidado.shape
print("\n" + "="*70)
print(f"✅ PASO 6.3 COMPLETADO: {archivo_05}")
print(f"📊 Variables actuales: {df_censo_consolidado.columns.tolist()}")
print(f"📊 Dataset actual: {filas} filas y {cols} columnas.")
print(f"🏠 Rango de tamaño de hogar: [{df_censo_consolidado['TAMANO_HOGAR_PROMEDIO'].min()} - {df_censo_consolidado['TAMANO_HOGAR_PROMEDIO'].max()}]")
print("="*70)

display(df_censo_consolidado.head(31))

,Zona_Nombre,Zona_Codigo,Family households (families),Married-couple family,"Male householder, no spouse present, family","Female householder, no spouse present, family",Nonfamily households,Households with one or more people under 18 years,Households with one or more people 65 years and over,Average household size,Average family size
0,Chelsea-Hudson Yards,MN0401,10741,7893,640,2208,25022,3657,7444,1.67,2.67
1,East Harlem (North),MN1102,12542,4660,1106,6776,15339,7308,7379,2.19,3.31
2,East Harlem (South),MN1101,12693,5073,1622,5998,13181,5508,8087,2.14,3.08
3,East Midtown-Turtle Bay,MN0604,9390,8209,249,932,13854,2773,8291,1.78,2.57
4,East Village,MN0303,9579,5407,969,3203,24112,3528,8141,1.83,2.80

======================================================================
✅ PASO 6.3 COMPLETADO: 05_Censo_Household_Type_Manhattan.csv
📊 Variables actuales: ['ID_ZONA', 'POBLACION_TOTAL', 'EDAD_MEDIANA', 'POBLACION_HISPANA', 'TAMANO_HOGAR_PROMEDIO']
📊 Dataset actual: 31 filas y 5 columnas.
🏠 Rango de tamaño de hogar: [1.61 - 2.63]
======================================================================

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,POBLACION_HISPANA,TAMANO_HOGAR_PROMEDIO
0,MN0401,61878,39.2,6004,1.67
1,MN1102,63526,36.6,21871,2.19
2,MN1101,58607,37.8,19369,2.14
3,MN0604,41969,45.6,1721,1.78
4,MN0303,68412,33.9,11928,1.83
5,MN0101,48608,34.3,1639,1.99
6,MN0602,26523,35.2,849,1.71
7,MN0202,31517,35.7,1003,1.74
8,MN0903,52530,38.0,19999,2.62
9,MN1002,86090,38.1,18165,2.26
10,MN1001,48803,38.3,6565,2.25
11,MN0402,55221,39.1,6556,1.61
12,MN1203,38209,38.5,23226,2.51
13,MN0302,46107,42.2,12016,2.05
14,MN0902,22260,34.5,9922,2.58
15,MN0501,29670,35.2,1493,1.65
16,MN0502,21949,42.8,1069,1.61
17,MN0901,37984,28.1,4722,2.12
18,MN0603,54905,34.3,2830,1.70
19,MN0201,22167,39.3,975,1.78
20,MN0601,21963,39.6,1097,2.05
21,MN0102,23257,36.8,873,2.20
22,MN0802,54062,50.0,2153,2.01
23,MN0801,79296,37.9,2959,1.87
24,MN0803,78950,42.2,4723,1.84
25,MN0702,99128,44.9,7618,2.03
26,MN0701,68212,43.2,3982,1.81
27,MN0703,51421,40.5,9724,2.14
28,MN1202,75554,40.0,37752,2.53
29,MN1201,74814,38.4,41937,2.63
30,MN0203,32518,39.7,2364,1.68

In [37]:
# PASO 6.4: BLOQUE CENSO - TASA DE EMPLEO

# 1. Carga e inspección
archivo_06 = "06_Censo_Employment_Status_Manhattan.csv"
path_06 = os.path.join(ruta_input, 'censo', archivo_06)
df_06_raw = pd.read_csv(path_06)

#Visualizamos
display(df_06_raw.head(5))

# 2. CÁLCULO DE LA TASA: (Employed / Pöpulation 16 years and over * 100
df_06_raw['TASA_EMPLEO'] = (
    df_06_raw['Employed'] / df_06_raw['Population 16 years and over']
) * 100

df_06_raw['TASA_EMPLEO'] = df_06_raw['TASA_EMPLEO'].round(2)

# 3. Selección y renombre
df_06_refinado = df_06_raw[['Zona_Codigo', 'TASA_EMPLEO']].copy()
df_06_refinado = df_06_refinado.rename(columns={'Zona_Codigo': 'ID_ZONA'})

# 4. UNIÓN AL CONSOLIDADO 
# Antes, borramos si existe por error previo
if 'TASA_EMPLEO' in df_censo_consolidado.columns:
    df_censo_consolidado = df_censo_consolidado.drop(columns=['TASA_EMPLEO'])

df_censo_consolidado = pd.merge(
    df_censo_consolidado, 
    df_06_refinado[['ID_ZONA', 'TASA_EMPLEO']], 
    on='ID_ZONA', 
    how='left'
)

# 4. Verificación de Calidad
filas, cols = df_censo_consolidado.shape
print("\n" + "="*70)
print(f"✅ PASO 6.4 COMPLETADO: {archivo_06}")
print(f"💼 Promedio de empleo en las zonas: {df_censo_consolidado['TASA_EMPLEO'].mean():.2f}%")
print(f"📊 Dataset actual: {filas} filas y {cols} columnas.")
print(f"💼 Rango detectado: [{df_censo_consolidado['TASA_EMPLEO'].min():.2f}% - {df_censo_consolidado['TASA_EMPLEO'].max():.2f}%]")
print("="*70)

display(df_censo_consolidado.head(31))

,Zona_Nombre,Zona_Codigo,Population 16 years and over,In labor force,Civilian labor force,Employed,Unemployed,Armed Forces,Not in labor force
0,Chelsea-Hudson Yards,MN0401,56623,42038,42023,39668,2355,15,14585
1,East Harlem (North),MN1102,51381,29337,29321,26225,3096,16,22044
2,East Harlem (South),MN1101,49182,27188,27188,24519,2669,0,21994
3,East Midtown-Turtle Bay,MN0604,37976,26897,26896,25303,1593,1,11079
4,East Village,MN0303,63253,40237,40223,37987,2236,14,23016

======================================================================
✅ PASO 6.4 COMPLETADO: 06_Censo_Employment_Status_Manhattan.csv
💼 Promedio de empleo en las zonas: 63.20%
📊 Dataset actual: 31 filas y 6 columnas.
💼 Rango detectado: [49.85% - 79.57%]
======================================================================

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,POBLACION_HISPANA,TAMANO_HOGAR_PROMEDIO,TASA_EMPLEO
0,MN0401,61878,39.2,6004,1.67,70.06
1,MN1102,63526,36.6,21871,2.19,51.04
2,MN1101,58607,37.8,19369,2.14,49.85
3,MN0604,41969,45.6,1721,1.78,66.63
4,MN0303,68412,33.9,11928,1.83,60.06
5,MN0101,48608,34.3,1639,1.99,79.57
6,MN0602,26523,35.2,849,1.71,68.32
7,MN0202,31517,35.7,1003,1.74,64.44
8,MN0903,52530,38.0,19999,2.62,61.43
9,MN1002,86090,38.1,18165,2.26,54.55
10,MN1001,48803,38.3,6565,2.25,63.21
11,MN0402,55221,39.1,6556,1.61,69.45
12,MN1203,38209,38.5,23226,2.51,63.16
13,MN0302,46107,42.2,12016,2.05,53.27
14,MN0902,22260,34.5,9922,2.58,52.18
15,MN0501,29670,35.2,1493,1.65,70.16
16,MN0502,21949,42.8,1069,1.61,65.59
17,MN0901,37984,28.1,4722,2.12,52.24
18,MN0603,54905,34.3,2830,1.70,71.82
19,MN0201,22167,39.3,975,1.78,70.97
20,MN0601,21963,39.6,1097,2.05,65.61
21,MN0102,23257,36.8,873,2.20,68.92
22,MN0802,54062,50.0,2153,2.01,59.30
23,MN0801,79296,37.9,2959,1.87,67.99
24,MN0803,78950,42.2,4723,1.84,65.92
25,MN0702,99128,44.9,7618,2.03,64.59
26,MN0701,68212,43.2,3982,1.81,64.80
27,MN0703,51421,40.5,9724,2.14,58.99
28,MN1202,75554,40.0,37752,2.53,60.63
29,MN1201,74814,38.4,41937,2.63,53.39
30,MN0203,32518,39.7,2364,1.68,71.17

In [38]:
# PASO 6.5: BLOQUE CENSO - INGRESO MEDIO

# 1. Carga e inspección
archivo_07 = "07_Censo_Income_Benefits_Manhattan.csv"
path_07 = os.path.join(ruta_input, 'censo', archivo_07)
df_07_raw = pd.read_csv(path_07)

# Visualizamos 
display(df_07_raw.head(5))

# 2. Selección
df_07_refinado = df_07_raw[['Zona_Codigo', 'Median household income (dollars)']].copy()

# Renombramos 
df_07_refinado = df_07_refinado.rename(columns={
    'Zona_Codigo': 'ID_ZONA',
    'Median household income (dollars)': 'INGRESO_MEDIANO_HOGAR'
})

df_07_refinado['INGRESO_MEDIANO_HOGAR'] = df_07_refinado['INGRESO_MEDIANO_HOGAR'].round(0)

# 3. UNIÓN AL CONSOLIDADO
# Antes, borramos si existe por error previo
if 'INGRESO_MEDIANO_HOGAR' in df_censo_consolidado.columns:
    df_censo_consolidado = df_censo_consolidado.drop(columns=['INGRESO_MEDIANO_HOGAR'])

df_censo_consolidado = pd.merge(
    df_censo_consolidado, 
    df_07_refinado, 
    on='ID_ZONA', 
    how='left'
)

# 4. Verificación de Calidad
filas, cols = df_censo_consolidado.shape
print("\n" + "="*70)
print(f"✅ PASO 6.5 COMPLETADO: {archivo_07}")
print(f"📊 Variables actuales: {df_censo_consolidado.columns.tolist()}")
print(f"📊 Dataset actual: {filas} filas y {cols} columnas.")
print(f"💰 Ingreso Mediano promedio en estas zonas: $[{df_censo_consolidado['INGRESO_MEDIANO_HOGAR'].min()} - {df_censo_consolidado['INGRESO_MEDIANO_HOGAR'].max()}]")
print("="*70)

display(df_censo_consolidado.head(31))

,Zona_Nombre,Zona_Codigo,Total households,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median household income (dollars),Mean household income (dollars)
0,Chelsea-Hudson Yards,MN0401,35763,1765,1555,1469,1110,2126,3976,2696,5300,4261,11505,126272.0,208851.0
1,East Harlem (North),MN1102,27881,4459,3524,3115,2048,2712,3926,2289,2695,1548,1565,39957.0,69405.0
2,East Harlem (South),MN1101,25874,3605,3113,2944,2032,2496,3384,1859,1969,1305,3167,42076.0,91582.0
3,East Midtown-Turtle Bay,MN0604,23244,1044,426,1103,653,1126,1330,2026,2787,2790,9959,170196.0,266919.0
4,East Village,MN0303,33691,3887,2400,2592,1296,2232,4321,2584,4080,3381,6918,76136.0,136990.0

======================================================================
✅ PASO 6.5 COMPLETADO: 07_Censo_Income_Benefits_Manhattan.csv
📊 Variables actuales: ['ID_ZONA', 'POBLACION_TOTAL', 'EDAD_MEDIANA', 'POBLACION_HISPANA', 'TAMANO_HOGAR_PROMEDIO', 'TASA_EMPLEO', 'INGRESO_MEDIANO_HOGAR']
📊 Dataset actual: 31 filas y 7 columnas.
💰 Ingreso Mediano promedio en estas zonas: $[39957.0 - 198961.0]
======================================================================

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,POBLACION_HISPANA,TAMANO_HOGAR_PROMEDIO,TASA_EMPLEO,INGRESO_MEDIANO_HOGAR
0,MN0401,61878,39.2,6004,1.67,70.06,126272.0
1,MN1102,63526,36.6,21871,2.19,51.04,39957.0
2,MN1101,58607,37.8,19369,2.14,49.85,42076.0
3,MN0604,41969,45.6,1721,1.78,66.63,170196.0
4,MN0303,68412,33.9,11928,1.83,60.06,76136.0
5,MN0101,48608,34.3,1639,1.99,79.57,198961.0
6,MN0602,26523,35.2,849,1.71,68.32,153720.0
7,MN0202,31517,35.7,1003,1.74,64.44,174062.0
8,MN0903,52530,38.0,19999,2.62,61.43,68527.0
9,MN1002,86090,38.1,18165,2.26,54.55,51386.0
10,MN1001,48803,38.3,6565,2.25,63.21,74007.0
11,MN0402,55221,39.1,6556,1.61,69.45,105839.0
12,MN1203,38209,38.5,23226,2.51,63.16,68523.0
13,MN0302,46107,42.2,12016,2.05,53.27,58841.0
14,MN0902,22260,34.5,9922,2.58,52.18,46819.0
15,MN0501,29670,35.2,1493,1.65,70.16,182280.0
16,MN0502,21949,42.8,1069,1.61,65.59,148446.0
17,MN0901,37984,28.1,4722,2.12,52.24,87452.0
18,MN0603,54905,34.3,2830,1.70,71.82,141463.0
19,MN0201,22167,39.3,975,1.78,70.97,132900.0
20,MN0601,21963,39.6,1097,2.05,65.61,160855.0
21,MN0102,23257,36.8,873,2.20,68.92,185902.0
22,MN0802,54062,50.0,2153,2.01,59.30,171961.0
23,MN0801,79296,37.9,2959,1.87,67.99,137355.0
24,MN0803,78950,42.2,4723,1.84,65.92,147475.0
25,MN0702,99128,44.9,7618,2.03,64.59,159333.0
26,MN0701,68212,43.2,3982,1.81,64.80,164712.0
27,MN0703,51421,40.5,9724,2.14,58.99,100165.0
28,MN1202,75554,40.0,37752,2.53,60.63,78465.0
29,MN1201,74814,38.4,41937,2.63,53.39,56929.0
30,MN0203,32518,39.7,2364,1.68,71.17,168629.0

In [39]:
# PASO 6.6: BLOQUE CENSO - OCUPACIÓN DE VIVIENDA

# 1. Carga e inspección
archivo_08 = "08_Censo_Housing_Occupancy_Manhattan.csv"
path_08 = os.path.join(ruta_input, 'censo', archivo_08)
df_08_raw = pd.read_csv(path_08)

#Visualizamos
display(df_08_raw.head(5))

# 2. CÁLCULO DE LA TASA DE OCUPACIÓN
# (Unidades Ocupadas / Unidades Totales) * 100
df_08_raw['TASA_OCUPACION'] = (
    df_08_raw['Occupied housing units'] / df_08_raw['Total housing units']
) * 100

# Redondeamos a 2 decimales como las variables anteriores
df_08_raw['TASA_OCUPACION'] = df_08_raw['TASA_OCUPACION'].round(2)

# 3. Seleccion
df_08_refinado = df_08_raw[['Zona_Codigo', 'TASA_OCUPACION']].rename(columns={'Zona_Codigo': 'ID_ZONA'})

# 4. UNIÓN AL CONSOLIDADO
# Limpiamos si ya existía por error
if 'TASA_OCUPACION' in df_censo_consolidado.columns:
    df_censo_consolidado = df_censo_consolidado.drop(columns=['TASA_OCUPACION'])

df_censo_consolidado = pd.merge(
    df_censo_consolidado, 
    df_08_refinado, 
    on='ID_ZONA', 
    how='left'
)

# 5. Verificación de Calidad
filas, cols = df_censo_consolidado.shape
print(f"✅ PASO 6.6 COMPLETADO: {archivo_08}")
print(f"📊 Variables actuales: {df_censo_consolidado.columns.tolist()}")
print(f"📊 Dataset actual: {filas} filas y {cols} columnas.")
print(f"🏠 Ocupación promedio en las zonas: [{df_censo_consolidado['TASA_OCUPACION'].min()} - {df_censo_consolidado['TASA_OCUPACION'].max()}]")
print("="*70)

display(df_censo_consolidado.head(31))

,Zona_Nombre,Zona_Codigo,Total housing units,Occupied housing units,Vacant housing units,Homeowner vacancy rate,Rental vacancy rate
0,Chelsea-Hudson Yards,MN0401,42625,35763,6862,3.6,6.3
1,East Harlem (North),MN1102,30668,27881,2787,4.9,5.1
2,East Harlem (South),MN1101,28997,25874,3123,2.4,3.8
3,East Midtown-Turtle Bay,MN0604,31825,23244,8581,8.1,7.6
4,East Village,MN0303,37020,33691,3329,0.7,3.7

✅ PASO 6.6 COMPLETADO: 08_Censo_Housing_Occupancy_Manhattan.csv
📊 Variables actuales: ['ID_ZONA', 'POBLACION_TOTAL', 'EDAD_MEDIANA', 'POBLACION_HISPANA', 'TAMANO_HOGAR_PROMEDIO', 'TASA_EMPLEO', 'INGRESO_MEDIANO_HOGAR', 'TASA_OCUPACION']
📊 Dataset actual: 31 filas y 8 columnas.
🏠 Ocupación promedio en las zonas: [67.98 - 93.98]
======================================================================

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,POBLACION_HISPANA,TAMANO_HOGAR_PROMEDIO,TASA_EMPLEO,INGRESO_MEDIANO_HOGAR,TASA_OCUPACION
0,MN0401,61878,39.2,6004,1.67,70.06,126272.0,83.90
1,MN1102,63526,36.6,21871,2.19,51.04,39957.0,90.91
2,MN1101,58607,37.8,19369,2.14,49.85,42076.0,89.23
3,MN0604,41969,45.6,1721,1.78,66.63,170196.0,73.04
4,MN0303,68412,33.9,11928,1.83,60.06,76136.0,91.01
5,MN0101,48608,34.3,1639,1.99,79.57,198961.0,83.10
6,MN0602,26523,35.2,849,1.71,68.32,153720.0,78.79
7,MN0202,31517,35.7,1003,1.74,64.44,174062.0,78.61
8,MN0903,52530,38.0,19999,2.62,61.43,68527.0,91.20
9,MN1002,86090,38.1,18165,2.26,54.55,51386.0,91.05
10,MN1001,48803,38.3,6565,2.25,63.21,74007.0,87.75
11,MN0402,55221,39.1,6556,1.61,69.45,105839.0,87.46
12,MN1203,38209,38.5,23226,2.51,63.16,68523.0,93.25
13,MN0302,46107,42.2,12016,2.05,53.27,58841.0,90.54
14,MN0902,22260,34.5,9922,2.58,52.18,46819.0,90.95
15,MN0501,29670,35.2,1493,1.65,70.16,182280.0,82.85
16,MN0502,21949,42.8,1069,1.61,65.59,148446.0,67.98
17,MN0901,37984,28.1,4722,2.12,52.24,87452.0,85.07
18,MN0603,54905,34.3,2830,1.70,71.82,141463.0,82.93
19,MN0201,22167,39.3,975,1.78,70.97,132900.0,82.01
20,MN0601,21963,39.6,1097,2.05,65.61,160855.0,92.47
21,MN0102,23257,36.8,873,2.20,68.92,185902.0,81.41
22,MN0802,54062,50.0,2153,2.01,59.30,171961.0,70.43
23,MN0801,79296,37.9,2959,1.87,67.99,137355.0,77.43
24,MN0803,78950,42.2,4723,1.84,65.92,147475.0,85.55
25,MN0702,99128,44.9,7618,2.03,64.59,159333.0,81.00
26,MN0701,68212,43.2,3982,1.81,64.80,164712.0,80.10
27,MN0703,51421,40.5,9724,2.14,58.99,100165.0,88.57
28,MN1202,75554,40.0,37752,2.53,60.63,78465.0,93.98
29,MN1201,74814,38.4,41937,2.63,53.39,56929.0,92.39
30,MN0203,32518,39.7,2364,1.68,71.17,168629.0,80.94

In [41]:
# PASO 7: CONSOLIDACIÓN FINAL DEL DATASET "CENSO"

# 1. uso del dataset consolidado
df_censo_final = df_censo_consolidado.drop(columns=['NOMBRE_ZONA'], errors='ignore').copy()

# 2. Definimos las variables de la Ficha del Censo 
ficha_censo = [
    'ID_ZONA', 
    'POBLACION_TOTAL', 
    'EDAD_MEDIANA',
    'INGRESO_MEDIANO_HOGAR', 
    'TASA_EMPLEO', 
    'TAMANO_HOGAR_PROMEDIO', 
    'POBLACION_HISPANA', 
    'TASA_OCUPACION'
]

# 3. Orden del DataFrame de Censo
df_censo_final = df_censo_final[ficha_censo].sort_values('ID_ZONA').reset_index(drop=True)

# 4. Verificación de coherencia
print("✅ Datos consolidados por ID_ZONA (Redundancia eliminada).")
display(df_censo_final.head(31))

# 5. Definir los nombres de archivo
nombre_sql = "CENSO.csv"

# Exportación a datos/base_datos/censo
df_censo_final.to_csv(os.path.join(ruta_sql, 'censo', nombre_sql), index=False, encoding='utf-8')


print("\n" + "="*70)
print("📂 EXPORTACIÓN COMPLETADA")
print(f"✅ Archivo para SQL: {nombre_sql}")
print("="*70)

✅ Datos consolidados por ID_ZONA (Redundancia eliminada).

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION
0,MN0101,48608,34.3,198961.0,79.57,1.99,1639,83.10
1,MN0102,23257,36.8,185902.0,68.92,2.20,873,81.41
2,MN0201,22167,39.3,132900.0,70.97,1.78,975,82.01
3,MN0202,31517,35.7,174062.0,64.44,1.74,1003,78.61
4,MN0203,32518,39.7,168629.0,71.17,1.68,2364,80.94
5,MN0302,46107,42.2,58841.0,53.27,2.05,12016,90.54
6,MN0303,68412,33.9,76136.0,60.06,1.83,11928,91.01
7,MN0401,61878,39.2,126272.0,70.06,1.67,6004,83.90
8,MN0402,55221,39.1,105839.0,69.45,1.61,6556,87.46
9,MN0501,29670,35.2,182280.0,70.16,1.65,1493,82.85
10,MN0502,21949,42.8,148446.0,65.59,1.61,1069,67.98
11,MN0601,21963,39.6,160855.0,65.61,2.05,1097,92.47
12,MN0602,26523,35.2,153720.0,68.32,1.71,849,78.79
13,MN0603,54905,34.3,141463.0,71.82,1.70,2830,82.93
14,MN0604,41969,45.6,170196.0,66.63,1.78,1721,73.04
15,MN0701,68212,43.2,164712.0,64.80,1.81,3982,80.10
16,MN0702,99128,44.9,159333.0,64.59,2.03,7618,81.00
17,MN0703,51421,40.5,100165.0,58.99,2.14,9724,88.57
18,MN0801,79296,37.9,137355.0,67.99,1.87,2959,77.43
19,MN0802,54062,50.0,171961.0,59.30,2.01,2153,70.43
20,MN0803,78950,42.2,147475.0,65.92,1.84,4723,85.55
21,MN0901,37984,28.1,87452.0,52.24,2.12,4722,85.07
22,MN0902,22260,34.5,46819.0,52.18,2.58,9922,90.95
23,MN0903,52530,38.0,68527.0,61.43,2.62,19999,91.20
24,MN1001,48803,38.3,74007.0,63.21,2.25,6565,87.75
25,MN1002,86090,38.1,51386.0,54.55,2.26,18165,91.05
26,MN1101,58607,37.8,42076.0,49.85,2.14,19369,89.23
27,MN1102,63526,36.6,39957.0,51.04,2.19,21871,90.91
28,MN1201,74814,38.4,56929.0,53.39,2.63,41937,92.39
29,MN1202,75554,40.0,78465.0,60.63,2.53,37752,93.98
30,MN1203,38209,38.5,68523.0,63.16,2.51,23226,93.25

======================================================================
📂 EXPORTACIÓN COMPLETADA
✅ Archivo para SQL: CENSO.csv
✅ Archivo para Proyecto: Censo_Proyecto.csv
======================================================================

In [42]:
# PASO 8: BLOQUE COSTO DE ALQUILER

import pandas as pd
import os

# 1. Carga e inspección
archivo_13 = "13_Costo_Alquiler_Manhattan.xlsx"
path_13 = os.path.join(ruta_input, 'alquiler', archivo_13)
df_13_raw = pd.read_excel(path_13)

# 1.1 Visualizamos 
display(df_13_raw.head(10))

# 2. SELECCIÓN Y RENOMBRADO 
df_alquiler_base = df_13_raw[['CODIGO_CENSO_NTA', 'PRECIO_PIES_CUADRADOS_ANUAL']].copy()
df_alquiler_base = df_alquiler_base.rename(columns={'CODIGO_CENSO_NTA': 'ID_ZONA'})

# 3. JOIN DIRECTO 
# Cruzamos con mapa_manhattan para que el nombre sea el del sistema
df_alquiler_final = pd.merge(
    mapa_manhattan[['ID_ZONA']], 
    df_alquiler_base, 
    on='ID_ZONA', 
    how='left'
)

# 4. LIMPIEZA: Rellenar nulos con CERO y redondear a 2 decimales
df_alquiler_final['PRECIO_PIES_CUADRADOS_ANUAL'] = df_alquiler_final['PRECIO_PIES_CUADRADOS_ANUAL'].fillna(0)
df_alquiler_final['PRECIO_PIES_CUADRADOS_ANUAL'] = df_alquiler_final['PRECIO_PIES_CUADRADOS_ANUAL'].round(2)

# 5. EXPORTACIÓN
df_sql = df_alquiler_final.dropna(subset=['PRECIO_PIES_CUADRADOS_ANUAL']).copy()
df_sql.to_csv(os.path.join(ruta_sql, 'alquiler', 'COSTO_ALQUILER.csv'), index=False)


print("\n" + "="*70)
print("✅ COSTO_ALQUILER COMPLETADO")
print(f"📊 Columnas: {df_alquiler_final.columns.tolist()}")
print(f"📊 Registros exportados a SQL: {len(df_sql)}")
print("="*70)

display(df_sql.head(31))

,NOMBRE_ZONA,CODIGO_CENSO_NTA,ZIP CODES,BARRIOS_INCLUIDOS,PRECIO_PIES_CUADRADOS_ANUAL,PRECIO_MES_LOCAL,FUENTE,LINK_FUENTE
0,Financial District-Battery Park City,MN0101,"10004, 10005, 10006, 10007, 10038","FiDi, Wall Street, WTC, Battery Park, Seaport",91.910000,15466.562500,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
1,Tribeca-Civic Center,MN0102,"10007, 10013","Tribeca, Civic Center, City Hall Area",122.722000,32769.239000,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
2,The Battery-Governors Island-Ellis Island-Libe...,MN0191,"10004 ,10280","South Ferry area, Battery Park City.",61.000000,13571.805556,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
3,SoHo-Little Italy-Hudson Square,MN0201,"10012, 10013","SoHo, Little Italy, Nolita, Hudson Square",190.540000,25993.451000,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
4,Greenwich Village,MN0202,"10011, 10014","South Village, West Village",99.027778,17666.666667,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
5,West Village,MN0203,10014,"West Village, Greenwich Village (West), Meatpa...",220.809989,31027.166667,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
6,Chinatown-Two Bridges,MN0301,"10002, 10038","Chinatown, Two Bridges, Confucius Plaza",61.800000,12005.833333,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
7,Lower East Side,MN0302,10002,"LES, Essex Crossing, Bowery (South)",107.900000,9668.541667,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
8,East Village,MN0303,"10003, 10009","East Village, Alphabet City, Loisaida, Tompkin...",127.584000,36959.766667,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...
9,Chelsea-Hudson Yards,MN0401,"10001, 10011","Chelsea, Hudson Yards, Penn Station, Meatpacki...",63.643137,12211.733333,-Loop Net/commercialcafe,https://www.loopnet.com/ - https://www.comme...

======================================================================
✅ COSTO_ALQUILER COMPLETADO
📊 Columnas: ['ID_ZONA', 'PRECIO_PIES_CUADRADOS_ANUAL']
📊 Registros exportados a SQL: 38
======================================================================

   ID_ZONA  PRECIO_PIES_CUADRADOS_ANUAL
0   MN0101                        91.91
1   MN0102                       122.72
2   MN0191                        61.00
3   MN0201                       190.54
4   MN0202                        99.03
5   MN0203                       220.81
6   MN0301                        61.80
7   MN0302                       107.90
8   MN0303                       127.58
9   MN0401                        63.64
10  MN0402                       126.14
11  MN0501                        68.50
12  MN0502                       199.67
13  MN0601                       140.00
14  MN0602                       138.33
15  MN0603                       190.00
16  MN0604                       220.00
17  MN0661                       210.00
18  MN0701                       110.00
19  MN0702                       101.77
20  MN0703                       165.00
21  MN0801                       184.09
22  MN0802                       200.00
23  MN0803                       170.00
24  MN0901                        76.36
25  MN0902                        55.36
26  MN0903                        95.00
27  MN1001                        70.00
28  MN1002                       110.00
29  MN1101                       240.67
30  MN1102                       100.00